=== promegan11/YRNWBPxmlGyak/yrnwbp_1015/kutyavilag1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cim" type="xs:string" />
    <xs:element name="szerzo" type="xs:string" />

    <xs:element name="nev" type="xs:string" />
    <xs:element name="baratja" type="xs:string" />
    <xs:element name="szuletett" type="xs:string" />
    <xs:element name="jellemzes" type="xs:string" />

    <xs:attribute name="isbn" type="xs:string" />

    <xs:element name="szereplo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nev" />
                <xs:element ref="baratja" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="szuletett" />
                <xs:element ref="jellemzes" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="konyv">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cim" />
                <xs:element ref="szerzo" />
                <xs:element ref="szereplo" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute ref="isbn" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== promegan11/YRNWBPxmlGyak/yrnwbp_1015/kutyavilag.xml
<?xml version="1.0" encoding="UTF-8"?>
<konyv isbn="0836217462" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kutyavilag1.xsd">
    <cim>Kutyavilág</cim>
    <szerzo>Charles M. Schulz</szerzo>
    <szereplo>
        <nev>Snoopy</nev>
        <baratja>Peppermint Patty</baratja>
        <szuletett>1950-10-04</szuletett>
        <jellemzes>Jellemzés</jellemzes>
    </szereplo>
    <szereplo>
        <nev>Peppermint Patty</nev>
        <szuletett>1966-08-22</szuletett>
        <jellemzes>Jellemzés</jellemzes>
    </szereplo>
</konyv>
